# Generated by Django 4.2.6 on 2023-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClimaSongs', '0002_weatherdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='pressure',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
