# Generated by Django 4.2.6 on 2023-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClimaSongs', '0003_alter_weatherdata_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(max_length=255)),
                ('song_name', models.CharField(max_length=255)),
            ],
        ),
    ]
